FROM ubuntu:18.04
LABEL user="jayson970613@qq.com"
# RUN apt-get update -y && apt-get install -y python-pip && pip install shadowsocks
CMD ls
WORKDIR /wuhu/
EXPOSE 8000 8080
COPY shadowsocks.json /etc/shadowsocks.json