apiVersion: v1
kind: Service
metadata:
  name: go-release-script
  namespace: devops
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31808
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: grpc
    nodePort: 31909
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: go-release-script
  sessionAffinity: None
  type: NodePort
