apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
    field.cattle.io/publicEndpoints: '[{"addresses":["10.1.8.54"],"port":32506,"protocol":"TCP","serviceName":"devops:mailman","allNodes":true},{"addresses":["10.1.8.54"],"port":30709,"protocol":"TCP","serviceName":"devops:mailman","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"mailman-manager","namespace":"devops"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mailman-manager"}},"template":{"metadata":{"labels":{"app":"mailman-manager"}},"spec":{"containers":[{"env":[{"name":"HTTP_PORT","value":"80"},{"name":"AMQP_ADDR","value":"rabbitmq.base:5672"},{"name":"AMQP_USER","valueFrom":{"secretKeyRef":{"key":"user","name":"rabbitmq"}}},{"name":"AMQP_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"rabbitmq"}}},{"name":"AMQP_EXCHANGE","value":"mailman"},{"name":"AMQP_QUEUE_PREFIX","value":"message"},{"name":"WXWORK_AGENTID","value":"1000134"}],"image":"registry.dg.com/devops/mailman-manager:latest","name":"mailman-manager","ports":[{"containerPort":80}]}],"imagePullSecrets":[{"name":"dockerdg"}]}}}}
  creationTimestamp: "2019-10-14T13:25:07Z"
  generation: 32
  labels:
    app: mailman-manager
  name: mailman-manager
  namespace: devops
  resourceVersion: "156999029"
  selfLink: /apis/apps/v1/namespaces/devops/deployments/mailman-manager
  uid: 0a4e038b-ee86-11e9-babc-5254003e747a
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: mailman-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mailman-manager
    spec:
      containers:
      - env:
        - name: HTTP_PORT
          value: "80"
        - name: GRPC_PORT
          value: "9090"
        - name: AMQP_ADDR
          value: rabbitmq.base
        - name: AMQP_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: rabbitmq
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: rabbitmq
        - name: AMQP_EXCHANGE
          value: mailman
        - name: AMQP_QUEUE_PREFIX
          value: message
        - name: WXWORK_AGENTID
          value: "1000134"
        - name: BROKER
          value: amqp
        image: registry.dg.com/devops/mailman-manager:latest
        imagePullPolicy: Always
        name: mailman-manager
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 9090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerdg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-10-14T13:25:07Z"
    lastUpdateTime: "2019-10-14T13:25:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 32
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
